language: ruby
rvm:
  # You can enable more than one ruby version target at the same time, but doing
  # so will disable code coverage reporting.
  # - "2.0.0"
  # - "2.1.5"
  # - "2.2.1"
  # - "2.3.0"
  - "2.4.2"
  # - "2.5.0" # dev
env:
  global:
    - CC_TEST_REPORTER_ID=fcda177928c42c93fd981f671305519ffb98b98c479198340ea67bc892ffd028
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - TESTOPTS="--verbose" bundle exec rake test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT --coverage-input-type simplecov
notifications:
  slack: galacticaactual:rhAXgZ68aoikbxBBA05xIUVC
